### PR TITLE
Clairvoyant Fox draft

### PR DESCRIPTION
**Pull request by McTsts**
draft for a role Ive wanted to make for a while.

### CODE REVIEW

**Comment by venomousbirds** [comment]
What ability do you think it should have?

**Comment by McTsts** [comment]
It's definitely some way of investigating. I think what we originally discussed was that it checks a players role and the pack is also informed of the results.

**Comment by Mjnstag** [comment]
sounds interesting. could make for an interesting dynamic between pack and fox. Maybe add a line about not being able to use it on their selves to let the pack know who they are, that would defeat the purpose of not being in the wolfpack imo

**Comment by McTsts** [comment]
oh yeah didn't notice that

**Comment by venomousbirds** [comment]
Added a description that might work

**Comment by McTsts** [comment]
> sounds interesting. could make for an interesting dynamic between pack and fox. Maybe add a line about not being able to use it on their selves to let the pack know who they are, that would defeat the purpose of not being in the wolfpack imo

ill add this as well, but other than that yours seems good 👍

**Review by venomousbirds — APPROVED** [review]

**Review by Dennis-0 — APPROVED** [review]

**Pull request merged**
