### PR TITLE
Update mayor

### LINKED ISSUE #107: Mayor >15
is this power actually useful?

### PR DESCRIPTION
**Pull request by McTsts**
Fixes #107

This sounds pretty terrible, can somebody try to improve the sentences?

### CODE REVIEW

**Comment by Shepherdwhen** [comment]
Both mayor's or just the <15 mayor?

**Comment by Shepherdwhen** [comment]
Oh wait it's just one role :s

**Comment by McTsts** [comment]
Yeah, there's only one role description.

**Comment by Mjnstag** [comment]
would there be any reason for the mayor to choose a different election order?

**Comment by McTsts** [comment]
> would there be any reason for the mayor to choose a different election order?

they could choose Reporter in case they die

**Comment by Mjnstag** [comment]
ah thats fair yea. Btw, if we accept this change, we will need to change a bunch of other roles that have the 2 mayor votes in their description like trickster/grandma

**Comment by McTsts** [comment]
> ah thats fair yea. Btw, if we accept this change, we will need to change a bunch of other roles that have the 2 mayor votes mentioned in their description like trickster/grandma

This only removes the 2 lynch power and not the 2 votes power.

**Comment by Shepherdwhen** [comment]
Is this basically a town flute player?

**Comment by McTsts** [comment]
> Is this basically a town flute player?

Is this for Innkeeper #166

**Comment by venomousbirds** [comment]
> If, by the start of the day, the chosen election isn't possible, because somebody is already elected as that role, elections will happen in the normal order.

what does this mean? it sounds a bit unclear

**Comment by McTsts** [comment]
> > If, by the start of the day, the chosen election isn't possible, because somebody is already elected as that role, elections will happen in the normal order.
> 
> what does this mean? it sounds a bit unclear

Assume a Mayor and Guardian alive
Mayor chooses Guardian for the next election
Option 1) Guardian dies during the night => Guardian Election (as chosen)
Option 2) Guardian lives => Reporter Election (according to normal order)

**Comment by McTsts** [comment]
Not sure how much I actually like this power. But I do think the double vote always being there makes sense.

**Review by kruthers — CHANGES_REQUESTED** [review]
I prefer the double votes as it gives more of a balancing act and the only real reason why you may change the order is if you are like a wolf and want to push the mayor vote back by a phase

**Comment by McTsts** [comment]
> I prefer the double votes as it gives more of a balancing act and the only real reason why you may change the order is if you are like a wolf and want to push the mayor vote back by a phase

With double votes, do you mean double lynch?

**Pull request closed without merging**
