### PR TITLE
Create Candlestick maker

### PR DESCRIPTION
**Pull request by Shepherdwhen**
An Idea for a Townsfolk group role that doesn't start as a group and instead makes it's own group

### CODE REVIEW

**Comment by venomousbirds** [comment]
This seems like Innkeeper but easier to get killed

**Comment by Shepherdwhen** [comment]
It's a bit different as:

- It doesn't have anonymous chat
- It loses control of who is added if there are more non town than town
- It can remove one person rather than everyone at once
- It doesn't delete what was said

**Comment by voidmist** [comment]
Consider naming the role Chandler:

> chandler (noun)
> _especially in the past_, a person who makes candles:
>
> [3rd definition](https://dictionary.cambridge.org/dictionary/english/chandler)

**Comment by Shepherdwhen** [comment]
> Consider naming the role Chandler:
> 
> > chandler (noun)
> > _especially in the past_, a person who makes candles:
> > [3rd definition](https://dictionary.cambridge.org/dictionary/english/chandler)

I based the name on the fact we have a butcher and a baker already and an old rhyme, one in the UK especially, has a line that goes "The Butcher, The Baker and The Candlestick maker"

**Comment by McTsts** [comment]
We've decided to not add this role. It seems fairly similar to Innkeeper and doesn't seem like it'd add anything unique.

**Pull request closed without merging**
