### PR TITLE
CC can be turned by non-lycan werewolves

### LINKED ISSUE #264: CC x Lone Warlock / Pack Tanner
If a Lone Warlock or Pack Tanner is chosen as the attacker of a wolfpack attack a Cursed Civilian wouldn't turn into a wolf.

### PR DESCRIPTION
**Pull request by McTsts**
Fixes #264

### CODE REVIEW

**Comment by Shepherdwhen** [comment]
We changed RH to include ferocious fox

**Comment by Mjnstag** [comment]
> We changed RH to include ferocious fox

i dont know how that is related, i mean like a DF being a fletchers customer, dying and then attacking the CC. They are on wolf team, but not a lycan or werewolf

**Comment by McTsts** [comment]
> > We changed RH to include ferocious fox
> 
> i dont know how that is related, i mean like a DF being a fletchers customer, dying and then attacking the CC. They are on wolf team, but not a lycan or werewolf

Foxes are werewolves

Wolf: The Role
Werewolf: A member of the werewolf team
Lycan: A wolf like role, usually closely related to the wolfpack/werewolf team
Wolfpack Member: A member of the wolfpack team
Fox: Not a wolf/lycan/wolfpack member, _but_ still a werewolf

**Comment by Mjnstag** [comment]
ah missed that

**Pull request merged**
