### PR TITLE
Create Frankenstein's Monster

### PR DESCRIPTION
**Pull request by bobloy**
Adds Frankenstein's monster, a reporter-like power that gathers abilities from the dead.

### CODE REVIEW

**Comment by Shepherdwhen** [comment]
This sounds like town version of reaper, and reaper sort of only just works as a solo

**Comment by McTsts** [comment]
This could just replace Reaper 
hepi

**Comment by Shepherdwhen** [comment]
It can be strong actually as it's a confirmed town reporter
!thonk

**Comment by Shepherdwhen** [comment]
how do you use emotes?

**Comment by Mjnstag** [comment]
> how do you use emotes?

upload an image in the comment
image

**Comment by venomousbirds** [comment]
This sounds more like reaper than a town role. I don't think a town role should be this powerful

**Comment by McTsts** [comment]
> This could just replace Reaper

This PR inspired me to make a new Reaper (an unfinished solo role) version!
I've combined this suggestion with it for the new version. I think this will work better there than as a townsfolk role. You can find that role under #283.

I'll close this because I think we're more likely to use #283 than this one, but thanks for giving us that idea!

**Pull request closed without merging**
