### PR TITLE
Create innkeeper

### PR DESCRIPTION
**Pull request by McTsts**
the role that was discussed on MW

### CODE REVIEW

**Comment by Mjnstag** [comment]
Would the inn be deleted/disbanded when the inkeeper dies?

**Comment by McTsts** [comment]
> Would the inn be deleted/disbanded when the inkeeper dies?

Hmm, good question. Probably should be?

**Comment by Mjnstag** [comment]
it probably should i think.

**Comment by Shepherdwhen** [comment]
Does that line mean that 3 flute players could enchant 3 people with 20 players?

**Comment by Shepherdwhen** [comment]
Wrong issue :s

**Comment by McTsts** [comment]
Changed that!

**Comment by McTsts** [comment]
This wasn't used all that much, but I don't really see anything that could go wrong with this. Doesn't really add anything new.

**Review by venomousbirds — APPROVED** [review]

**Pull request merged**
