### PR TITLE
Hellhound Betrayal

### PR DESCRIPTION
**Pull request by McTsts**
This change would make the role a bit more useful than it currently is, without really changing it too much.

### CODE REVIEW

**Comment by venomousbirds** [comment]
disbandment sounds good to me

**Comment by Shepherdwhen** [comment]
so if a hellhound becomes a vampire basically, or if an infected wolf with hellhound targets a demon/devil I guess, but I like the idea that it's a complete trust team

**Comment by McTsts** [comment]
I think with normal roles the only possibilities are Undead and Cupid.

**Comment by Shepherdwhen** [comment]
Oh yeah cupid turns them into solo

**Pull request merged**
