### PR TITLE
Create Jack Robinson and Robin Jackson

### PR DESCRIPTION
**Pull request by McTsts**
Bringing back two beloved roles that were removed for some reason.

### CODE REVIEW

**Comment by venomousbirds** [comment]
They were removed for a reason, let's not add it back

**Comment by McTsts** [comment]
> They were removed for a reason, let's not add it back

:(

**Comment by venomousbirds** [comment]
thight

**Comment by Shepherdwhen** [comment]
Suggestion to add a role called "Jackson Robin Robinson Jack" that loses if either die but wins with townsfolk

**Comment by venomousbirds** [comment]
How can i delete this from existence?

**Review by venomousbirds — CHANGES_REQUESTED** [review]
Delete this

**Comment by Shepherdwhen** [comment]
> How can i delete this from existence?

Go to github headquarters, find the server location the either 1) start a fire 2) delete it from the server 3) kick the server in

**Comment by McTsts** [comment]
> Suggestion to add a role called "Jackson Robin Robinson Jack" that loses if either die but wins with townsfolk

I'd prefer "Jack Robin Robinson Jackson" or something like that, has first/last names order correctly

**Comment by McTsts** [comment]
> Delete this

It contains neither jack nor robin nor jackson nor robinson :(

**Comment by venomousbirds** [comment]
And still the idea is quite awful

**Comment by McTsts** [comment]
> And still the idea is quite awful

No, it's not :)

**Comment by Shepherdwhen** [comment]
> > Suggestion to add a role called "Jackson Robin Robinson Jack" that loses if either die but wins with townsfolk
> 
> I'd prefer "Jack Robin Robinson Jackson" or something like that, has first/last names order correctly

Good point what about "Jack Jack Jack Robin Jack Robin Jackson Robinson JackRobinson"

**Comment by venomousbirds** [comment]
This is in no way town aligned, it makes no sense and i hate both of you 
pensivethight

**Comment by McTsts** [comment]
> > > Suggestion to add a role called "Jackson Robin Robinson Jack" that loses if either die but wins with townsfolk
> > 
> > 
> > I'd prefer "Jack Robin Robinson Jackson" or something like that, has first/last names order correctly
> 
> Good point what about "Jack Jack Jack Robin Jack Robin Jackson Robinson JackRobinson"

Interesting suggestion.

**Comment by McTsts** [comment]
> This is in no way town aligned, it makes no sense and i hate both of you
> pensivethight

It is town aligned!

**Comment by venomousbirds** [comment]
Why the fuck would town want other town dead? I hate this

**Comment by McTsts** [comment]
> Why the fuck would town want other town dead? I hate this

What would it be if not town.

**Comment by Shepherdwhen** [comment]
> Why the fuck would town want other town dead? I hate this

Because why would you want a specific player to win if they want to make you lose

**Comment by venomousbirds** [comment]
UA

**Comment by McTsts** [comment]
Being aligned with town is not UA

**Comment by Shepherdwhen** [comment]
> > Why the fuck would town want other town dead? I hate this
> 
> What would it be if not town.

Wolves 😂

**Comment by Shepherdwhen** [comment]
or even solo

**Comment by venomousbirds** [comment]
ITS NOT TOWN. Townsfolk wins with other townsfolk. This role needs to have other town dead to win??? Makes no sense at all I hate this

**Comment by McTsts** [comment]
It's a mixture of baker and butcher but with a more interesting dynamic

**Comment by Shepherdwhen** [comment]
> ITS NOT TOWN. Townsfolk wins with other townsfolk. This role needs to have other town dead to win??? Makes no sense at all I hate this

Doesn't the FA need a TI to die to become useful? therefore how is FA town

**Comment by venomousbirds** [comment]
This makes no sense. Town needing town dead to win? This is horrible I hate it

**Comment by venomousbirds** [comment]
> > ITS NOT TOWN. Townsfolk wins with other townsfolk. This role needs to have other town dead to win??? Makes no sense at all I hate this
> 
> Doesn't the FA need a TI to die to become useful? therefore how is FA town

It doesnt need TI dead. It can survive without TI dying. It can win without TI dying.

**Comment by McTsts** [comment]
There's other roles that don't conform to standard win conditions (Gray Werewolf, Immune Survivor)

**Comment by venomousbirds** [comment]
Gray Werewolf is Solo, and that makes sense in that case. Immune survivor is UA, and UA doesn't have standard win conditions. This role you're suggesting is closer to Immune survivor wincon (UA) than town

**Comment by Shepherdwhen** [comment]
> There's other roles that don't conform to standard win conditions (Gray Werewolf, Immune Survivor)

Don't forget Cupid which technically has a town wincon therefore proving the idea to work on a technicality

**Comment by Shepherdwhen** [comment]
because cupid + wolf needs townsfolk dead when it has a townsfolk wincon and could theoretically win with town

**Comment by McTsts** [comment]
Cupid not being a townsfolk role (like it used to be) also has caused quite a bit of confusion

**Comment by McTsts** [comment]
(It was changed from Townsfolk to Unaligned without changing how the role works)

**Comment by venomousbirds** [comment]
Cupid is still unaligned, it's listed as unaligned so it counts as UA. it just defaults to town wincon, but that doesn't mean it's a townsfolk role

**Comment by Shepherdwhen** [comment]
This is basically an anti cupid

**Comment by McTsts** [comment]
> Cupid is still unaligned, it's listed as unaligned so it counts as UA. it just defaults to town wincon, but that doesn't mean it's a townsfolk role

And it being listed as UA always causes confusion

**Comment by venomousbirds** [comment]
This role is just the worst thing and should not be added at all. The idea is bad, it doesn't fit in the ww style. And it's definitely not townsfolk

**Comment by venomousbirds** [comment]
Why is cupid as UA confusing? It makes sense. It can become anything.

**Comment by venomousbirds** [comment]
(any wincon)

**Comment by McTsts** [comment]
> This role is just the worst thing and should not be added at all. The idea is bad, it doesn't fit in the ww style. And it's definitely not townsfolk

It doesn't clash with the Townsfolk win condition.

**Comment by McTsts** [comment]
> Why is cupid as UA confusing? It makes sense. It can become anything.

No it can't. It's always Townsfolk aligned, unless it changes role.

**Comment by McTsts** [comment]
The couple combines the win conditions (Cupid's town alignment and e.g. Wolf's werewolf alignment) into the actual alignment of the couple

**Comment by venomousbirds** [comment]
God this is tiring. Let's not add this role because Town needing to have other Town dead just makes absolutely no sense

**Comment by Shepherdwhen** [comment]
> Why is cupid as UA confusing? It makes sense. It can become anything.

it can't tho it can become town, solo or hell, and by role changes it can be wolf or undead

**Comment by venomousbirds** [comment]
> > Why is cupid as UA confusing? It makes sense. It can become anything.
> 
> it can't tho it can become town, solo or hell, and by role changes it can be wolf or undead

That's what I said?

**Comment by Shepherdwhen** [comment]
> > > Why is cupid as UA confusing? It makes sense. It can become anything.
> > 
> > 
> > it can't tho it can become town, solo or hell, and by role changes it can be wolf or undead
> 
> That's what I said?

any role can become wolf or undead though, and cupid can make any non townsfolk a solo the only difference is devil in cupid

**Comment by McTsts** [comment]
Cupid can never be anything other than town aligned, in combination with a non-town this can become a solo win condition. If the Cupid loses their role and becomes a Wolf or Undead it changes alignment to wolf/underworld. It cannot become flute, pyro, disease, nightmare, flock, graveyard or ice royal aligned. Additionally they technically also can't become heaven/hell aligned and just lose if they select a member of those teams.

**Comment by venomousbirds** [comment]
Cupid is listed as unaligned and can change wincon depending on who they choose. When they change wincon, they can't win with town anymore. This role you're suggesting will stay town with a town wincon even thought they have to kill town. This makes absolutely no sense to me because they're still town and they keep the town wincon. They don't betray town and have a different wincon, like cupid can. They're a town group that has to kill their town group. Can't you see that that's completely wrong and not like a typical town at all? Bakers don't have to kill eachother, they work together to make town win. Rivals can work together but at some point have to die and lose, even though their wincon is town. This is unaligned behaviour

**Comment by venomousbirds** [comment]
Now stop fucking around, this role is awful

**Comment by McTsts** [comment]
> Cupid is listed as unaligned and can change wincon depending on who they choose. When they change wincon, they can't win with town anymore. This role you're suggesting will stay town with a town wincon even thought they have to kill town. This makes absolutely no sense to me because they're still town and they keep the town wincon. They don't betray town and have a different wincon, like cupid can. They're a town group that has to kill their town group. Can't you see that that's completely wrong and not like a typical town at all? Bakers don't have to kill eachother, they work together to make town win. Rivals can work together but at some point have to die and lose, even though their wincon is town. This is unaligned behaviour

This PR is already closed. Cupid is _listed_ as Unaligned, but is town aligned.

**Pull request closed without merging**
