### PR TITLE
Remake of corrupt wolf

### PR DESCRIPTION
**Pull request by venomousbirds**

### CODE REVIEW

**Comment by venomousbirds** [comment]
thingy for #639

**Review by Mjnstag — COMMENTED** [review]
idk if stealing would be the correct word if the corrupt wolf can also give the selected player 2 votes

**Comment by venomousbirds** [comment]
any suggestions on what it could be instead?

**Comment by McTsts** [comment]
manipulate, maybe?

**Review by cryptidjayden — APPROVED** [review]

**Pull request merged**
