### PR TITLE
Spirit as Reaper Recruit role + Less reaper recruit

### LINKED ISSUE #612: Wraith votes
> wraith recruiting should remove wraith vote

@McTsts

### PR DESCRIPTION
**Pull request by ThomasRubycrust**
Fixes #612

### CODE REVIEW

**Comment by venomousbirds** [comment]
>Passive abilities of solo teams (e.g. the flute player passively obstructs enchanted player to see flute player as a result) also apply to the Reaper, but only when the last member of a team has died, however they work with elements of the nightmare team instead (e.g. a flute player ability using reaper obstructs sleepless players to see reaper as a result). 
If an ability results in a role change (e.g. Look-Alike), no role change happens, instead a permanent strong disguise of the role that the player would have turned into is applied to the player. The Reaper is informed which disguise is being used. An exception is all role changes that would recruit another player on that role's team, in that case the role change still happens, but the player is turned into a spirit instead (e.g. Vampire, Infecting Wolf).

**Comment by ThomasRubycrust** [comment]
> > Passive abilities of solo teams (e.g. the flute player passively obstructs enchanted player to see flute player as a result) also apply to the Reaper, **but only when the last member of a team has died,** however they work with elements of the nightmare team instead (e.g. a flute player ability using reaper obstructs sleepless players to see reaper as a result).
> > If an ability results in a role change (e.g. Look-Alike), no role change happens, instead a permanent strong disguise of the role that the player would have turned into is applied to the player. The Reaper is informed which disguise is being used. An exception is all role changes that would recruit another player on that role's team, in that case the role change still happens, but the player is turned into a spirit instead (e.g. Vampire, Infecting Wolf).
> 
> very long text but i dont really understand the bold part?

If there's a Vampire and an Undead, and the Vampire dies, the Reaper gains the power to turn people sleepless from the Vampire, but not the passive demonize effect. Once the Undead also dies (last team member), they gain the passive effect (recruitment)

**Comment by venomousbirds** [comment]
oh okay thats allright

**Review by cryptidjayden — COMMENTED** [review]
> Passive abilities of solo teams (e.g. the flute player passively obstructs enchanted player to see flute player as a result) also apply to the Reaper, but only when the last member of a team has died, however they work with elements of the nightmare team instead (e.g. a flute player ability using reaper obstructs sleepless players to see reaper as a result). 
If an ability results in a role change (e.g. Look-Alike), no role change happens, instead a permanent strong disguise of the role that the player would have turned into is applied to the player. The Reaper is informed which disguise is being used. An exception is all role changes that would recruit another player on that role's team, in that case the role change still happens, but the player is turned into a spirit instead (e.g. Vampire, Infecting Wolf).

change grammar to:
> Passive abilities of solo teams (e.g. the flute player passively obstructs enchanted player to see flute player as a result) also apply to the Reaper, but only when the last member of a team has died. They work with elements of the nightmare team (e.g. a flute player ability using reaper obstructs sleepless players to see reaper as a result). 
If an ability results in a role change (e.g. Look-Alike), no role change happens. Instead, a permanent strong disguise of the role that the player would have turned into is applied to the player. The Reaper is informed which disguise is being used. An exception is all role changes that would recruit another player on that role's team; the role change still happens, but the player is turned into a spirit (e.g. Vampire, Infecting Wolf).

**Comment by cryptidjayden** [comment]
i dont need you "help" i figured it out on my own because i am SO COOL B)

**Review by venomousbirds — APPROVED** [review]

**Comment by McTsts** [comment]
I added #607 into this

**Review by venomousbirds — APPROVED** [review]

**Review by cryptidjayden — APPROVED** [review]

**Pull request merged**
