### PR TITLE
Remove Gray Werewolf

### PR DESCRIPTION
**Pull request by McTsts**
This is a very unpopular role that is rarely used. I feel like this role encourages some sort of gamethrowing? (The other play wins with the GWW but their team loses?) That's just a strange and bad mechanic.

### CODE REVIEW

**Comment by venomousbirds** [comment]
I think we can maybe change GWW, it would be nice to have another www-like role, but i do agree the wincon seems weird

**Comment by McTsts** [comment]
It could be changed, but I'm not sure how? Right now it's just off-brand white werewolf

**Comment by cryptidjayden** [comment]
Yeah, right now GWW is fucking useless outside of mini wolves. We can always create another WWW-like role later and name it that, but there's no point keeping this around til then.

**Comment by McTsts** [comment]
Yeah, I agree. @venomousbirds is it fine if we remove it for now?

**Comment by venomousbirds** [comment]
sure

**Pull request merged**
