### PR TITLE
Create corrupt wolf

### PR DESCRIPTION
**Pull request by McTsts**
this is an ability from the generator, could work as a proper role since we don't have a huge selection of wolf roles

### CODE REVIEW

**Review by venomousbirds — APPROVED** [review]
i like the idea of wolves being able to control elections and town being able to control lynches (saboteur and royal wolf for wolves and exe, child, rk for town)
seems like a good role, will give some variety to wolfpack

**Comment by venomousbirds** [comment]
wait unapprove this for a second, what the hell is the reveal thing

**Comment by McTsts** [comment]
> i like the idea of wolves being able to control elections and town being able to control lynches (saboteur and royal wolf for wolves and exe, child, rk for town)
> seems like a good role, will give some variety to wolfpack

That's actually a neat observation - hadn't noticed that before.

**Comment by McTsts** [comment]
> wait unapprove this for a second, what the hell is the reveal thing

You can use it against WWW 
joy

**Comment by venomousbirds** [comment]
but yeah i dont think the reveal thing should be a thing

**Comment by Shepherdwhen** [comment]
> wait unapprove this for a second, what the hell is the reveal thing

"Yes I want to publicly reveal myself as wolf" said no sane person

**Comment by venomousbirds** [comment]
hello my fellow participants of werewolves. i am the royal wolf and i will now cancel this election. town killing, please target me, ive already given up, my wolfpack is stupid.

**Comment by Shepherdwhen** [comment]
> > wait unapprove this for a second, what the hell is the reveal thing
> 
> You can use it against WWW
> joy

www doesn't cc Wolf Power roles anyway since it's disguised as wolf and gets in 1 v 1's which it doesn't want

**Comment by venomousbirds** [comment]
everytime i see that giant joy emote i die a little inside

**Comment by Shepherdwhen** [comment]
unless it reveals to wolfpack but other than that it's an insane move, unless wolves have already won I.e They know the last solo and just want to screw with town because royal wolf is still alive and unused

**Comment by McTsts** [comment]
> > > wait unapprove this for a second, what the hell is the reveal thing
> > 
> > 
> > You can use it against WWW
> > joy
> 
> www doesn't cc Wolf Power roles anyway since it's disguised as wolf and gets in 1 v 1's which it doesn't want

Good point

**Comment by McTsts** [comment]
That's why this is a draft and not a PR rn 
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image

**Comment by venomousbirds** [comment]
ts i will murder you
this is a serious threat

**Comment by McTsts** [comment]
> ts i will murder you
> this is a serious threat

Thanks for providing evidence!

**Comment by venomousbirds** [comment]
if ts ever gets murdered im gonna get blamed

**Comment by McTsts** [comment]
> wait unapprove this for a second, what the hell is the reveal thing

Removed that. Making this a PR now

**Review by venomousbirds — APPROVED** [review]

**Comment by McTsts** [comment]
Renamed to Corrupt Wolf as suggested in #202

**Review by venomousbirds — APPROVED** [review]

**Review by Dennis-0 — APPROVED** [review]

**Pull request merged**
