### PR TITLE
Suggestion for a completely new Reaper

### PR DESCRIPTION
**Pull request by McTsts**
This is a mixture of the previous Reaper and #186 Frankenstein's Monster with a bunch of extra clarification to get rid of edge cases

### CODE REVIEW

**Comment by Shepherdwhen** [comment]
Why would it not have the anonymous communication?

**Comment by McTsts** [comment]
> Why would it not have the anonymous communication?

It could theoretically have it. An alternative suggestion to my anonymous communication solution is that the reaper gets _1_ anonymous communication thing and if it somehow uses several anonymous communication powers in one night all targeted players are just added to that.

**Comment by Shepherdwhen** [comment]
> > Why would it not have the anonymous communication?
> 
> It could theoretically have it. An alternative suggestion to my anonymous communication solution is that the reaper gets _1_ anonymous communication thing and if it somehow uses several anonymous communication powers in one night all targeted players are just added to that.

It could be put into the dead players talking channel theoretically, but the only one to not work would be flute player I guess

**Comment by McTsts** [comment]
> > > Why would it not have the anonymous communication?
> > 
> > 
> > It could theoretically have it. An alternative suggestion to my anonymous communication solution is that the reaper gets _1_ anonymous communication thing and if it somehow uses several anonymous communication powers in one night all targeted players are just added to that.
> 
> It could be put into the dead players talking channel theoretically, but the only one to not work would be flute player I guess

not sure what you mean

**Comment by Shepherdwhen** [comment]
> > > > Why would it not have the anonymous communication?
> > > 
> > > 
> > > It could theoretically have it. An alternative suggestion to my anonymous communication solution is that the reaper gets _1_ anonymous communication thing and if it somehow uses several anonymous communication powers in one night all targeted players are just added to that.
> > 
> > 
> > It could be put into the dead players talking channel theoretically, but the only one to not work would be flute player I guess
> 
> not sure what you mean

When the stalker dies why can the reaper not be added to the dead stalker's stalker_talk chat?

**Comment by Shepherdwhen** [comment]
Channel*

**Comment by McTsts** [comment]
> > > > > Why would it not have the anonymous communication?
> > > > 
> > > > 
> > > > It could theoretically have it. An alternative suggestion to my anonymous communication solution is that the reaper gets _1_ anonymous communication thing and if it somehow uses several anonymous communication powers in one night all targeted players are just added to that.
> > > 
> > > 
> > > It could be put into the dead players talking channel theoretically, but the only one to not work would be flute player I guess
> > 
> > 
> > not sure what you mean
> 
> When the stalker dies why can the reaper not be added to the dead stalker's stalker_talk chat?

That could work actually, not sure if we want to do it though

**Comment by MrTurtleJr** [comment]
I'm not sure I get line 18. The Reaper can choose to give poisoned food to a player and then make the player eat it?

**Comment by McTsts** [comment]
> I'm not sure I get line 18. The Reaper can choose to give poisoned food to a player and then make the player eat it?

Yes, that was the idea.

**Comment by venomousbirds** [comment]
That might be a little overpowered. The player is sleepless anyways because it's chosen, so why not give it a choice of what to do?

**Comment by MrTurtleJr** [comment]
> 
> 
> That might be a little overpowered. The player is sleepless anyways because it's chosen, so why not give it a choice of what to do?

Yeah, I think that may be a bit weird... also letting a player kill themselves through wager because they are controlled by the Reaper is a tad bit confusing. In my opinion the Reaper should let the chosen player choose what option to go with.

**Comment by McTsts** [comment]
How about this then: The reaper gets 1 anonymous communication thing and if it somehow uses several anonymous communication powers in one night all targeted players are just added to that.

**Comment by McTsts** [comment]
Basically, they'd know the offer is from the Reaper

**Comment by Shepherdwhen** [comment]
Should wraith get the "fail and die if a sleepless power is used on them" power?

Just feels like a small buff it could have, that or any sleepless attacker on the wraith fails

**Comment by McTsts** [comment]
> Should wraith get the "fail and die if a sleepless power is used on them" power?
> 
> Just feels like a small buff it could have, that or any sleepless attacker on the wraith fails

Oh yeah, good idea.

**Comment by Shepherdwhen** [comment]
What would happen with day specific or like team specific abilities?

Examples being royal knight or the new alpha wolf

**Comment by Shepherdwhen** [comment]
It seems a bit overpowered if the reaper can choose who the wolves kill one night

**Comment by Shepherdwhen** [comment]
I'm going to make a list of questions
Would the reaper die if it got a lone wolf kill and attacked a wolf?
Would the reaper die if it priest watered town?
If a player sold their soul can they then get a second power that requires soul selling from reaper wager?
Does reaper learn your identity if you use a reaper wager to invest?
Does just receiving a reaper wager turn you sleepless?
What does reaper receive from wolf, is it a kill like old reaper?
Does reaper receive the original role or the last role the player had?
If a sleepless pyro ignites and reaper is powdered does the pyro die?
Is the reaper and wraith immune to sleeplessness via redirection?
Are all investigations through the dead player or the reaper?

**Comment by McTsts** [comment]
> What would happen with day specific or like team specific abilities?
> 
> Examples being royal knight or the new alpha wolf

Royal Knight - The Reaper can cancel the lynch (RK power can be used at night)
Other day abilities: "Any immediate day or end day abilities turn into immediate night and end night abilities."
Alpha Wolf - The Reaper would gain 2 votes if they somehow managed to be part of a group with a poll


> It seems a bit overpowered if the reaper can choose who the wolves kill one night

They can't as the wolfpack kill isn't connected to any role specifically. Also: "Group roles don't give the reaper any powers"

> I'm going to make a list of questions
> Would the reaper die if it got a lone wolf kill and attacked a wolf?

Yes.

> Would the reaper die if it priest watered town?

Yes.

> If a player sold their soul can they then get a second power that requires soul selling from reaper wager?

There can never be more than 1 reaper wager as there can never be more than 1 devil, nor more than 1 reaper.

> Does reaper learn your identity if you use a reaper wager to invest?

Yes.

> Does just receiving a reaper wager turn you sleepless?

Yes.

> What does reaper receive from wolf, is it a kill like old reaper?

Nothing. Wolf has no abilities. Also: "Group roles don't give the reaper any powers"

> Does reaper receive the original role or the last role the player had?

The last role.

> If a sleepless pyro ignites and reaper is powdered does the pyro die?

Yes.

> Is the reaper and wraith immune to sleeplessness via redirection?

Fixed that. Now they can't become sleepless.

> Are all investigations through the dead player or the reaper?

All effects are executed by the Reaper. So they're seen from the Reaper's point of view.

**Comment by Shepherdwhen** [comment]
> > It seems a bit overpowered if the reaper can choose who the wolves kill one night
>
> They can't as the wolfpack kill isn't connected to any role specifically. Also: "Group roles don't give the reaper any powers"

I meant the new alpha wolf idea that can control the pack kill once per game, I'm future-proofing

**Comment by McTsts** [comment]
> > > It seems a bit overpowered if the reaper can choose who the wolves kill one night
> > 
> > 
> > They can't as the wolfpack kill isn't connected to any role specifically. Also: "Group roles don't give the reaper any powers"
> 
> I meant the new alpha wolf idea that can control the pack kill once per game, I'm future-proofing

Forgot that existed. In that case, yes, the Reaper could overwrite the pack's kill assuming the Alpha Wolf dies without using their ability.

**Review by venomousbirds — APPROVED** [review]

**Pull request merged**
