### PR TITLE
Change weird Wisp behaivor

### LINKED ISSUE #552: Wisp weird behaivor
If the wisp tries to powder someone its immediate, however if their target is already powdered its an end effect. While this is consistent, it's a bit weird, because technically we cant confirm the wisp's action if it results in igniting and the wisp could use this to realize the person is already powdered and instead powder someone else. I think both abilities should just be end-day.

### PR DESCRIPTION
**Pull request by ThomasRubycrust**
Fixes #552

### CODE REVIEW

**Comment by venomousbirds** [comment]
imo its more consistent to just leave it the old way and maybe note that the wisp will only be informed if they powdered or ignited at the end of the phase

**Comment by ThomasRubycrust** [comment]
I prefer my solution, but yours works too.

**Comment by venomousbirds** [comment]
Someone else should have a look at it then

**Comment by McTsts** [comment]
> imo its more consistent to just leave it the old way and maybe note that the wisp will only be informed if they powdered or ignited at the end of the phase

Changed to this

**Review by venomousbirds — APPROVED** [review]

**Pull request merged**
