### PR TITLE
Update clairvoyant fox

### PR DESCRIPTION
**Pull request by McTsts**
As discussed in #155
I also added a thing so pack cant kill them

### CODE REVIEW

**Comment by Shepherdwhen** [comment]
> As discussed in #155
> I also added a thing so pack cant kill them

That seems like they have no reason to join pack since wolves can't really kill them so they will stay CF for ages

**Comment by Shepherdwhen** [comment]
> > As discussed in #155
> > I also added a thing so pack cant kill them
> 
> That seems like they have no reason to join pack since wolves can't really kill them so they will stay CF for ages

I didn't read it fully no it works lol

**Comment by McTsts** [comment]
hmm, possibly, but on the other hand as long as they don't join their info is also worthless

**Comment by Shepherdwhen** [comment]
> hmm, possibly, but on the other hand as long as they don't join their info is also worthless

I just misread the part about forced wolf so I thought it was just like a runner not a cc

**Pull request merged**
