### PR TITLE
CH protect against any wronging

### LINKED ISSUE #430: Cautious Hag Spell
maybe Cautious could protect against any type of wronging

### PR DESCRIPTION
**Pull request by McTsts**
Fixes #430

### CODE REVIEW

**Comment by McTsts** [comment]
resolved conflict

**Comment by venomousbirds** [comment]
I assume this is only specific to CH protecting another Hag?

**Comment by McTsts** [comment]
I believe it was meant that any player could be protected from any effect that would count as wronging if it was used on a hag

**Comment by McTsts** [comment]
Though that specific power could also only be specific to hags (that was the purpose of the change)

**Comment by venomousbirds** [comment]
I think it would make more sense for it to only count for hags, I don't think it makes sense to make a protect that is as strong as this for just anyone

**Comment by McTsts** [comment]
Changed it

**Review by venomousbirds — APPROVED** [review]
Sounds good, hags being able to help eachother like this and staying unwronged for longer is a nice addition

**Pull request merged**
