### PR TITLE
Dog & Cursed Civilian

### PR DESCRIPTION
**Pull request by venomousbirds**
What cursed civilian are we adding for dog? Names differ from "very cursed civilian" (quite unoriginal and bland naming) to "Cursed Civilian (Old)" (also very unoriginal but less confusing)

### CODE REVIEW

**Comment by McTsts** [comment]
I'd say we add back old CC as a proper role - I've made changes to this branch to do that

**Comment by McTsts** [comment]
@venomousbirds please check my changes when you have time and merge if my changes are fine

**Review by McTsts — APPROVED** [review]

**Review by Mjnstag — APPROVED** [review]

**Comment by Mjnstag** [comment]
iirc, there was talk about not telling cursed civillians if they were cc or normal citizen, did we want to use that?

**Comment by McTsts** [comment]
I don't really like that

**Comment by Dennis-0** [comment]
"they may betray their team at some point" and "they may betray their team at any moment".
Is this supposed to be different?

**Comment by McTsts** [comment]
probably not

**Comment by McTsts** [comment]
> "they may betray their team at some point" and "they may betray their team at any moment".
> Is this supposed to be different?

made it consistent 👍

**Review by Dennis-0 — APPROVED** [review]

**Pull request merged**
