### PR TITLE
Horseman Solo Team

### PR DESCRIPTION
**Pull request by McTsts**
A solo team consisting of 4 different roles, however they need not all exist at the same time.

### CODE REVIEW

**Comment by McTsts** [comment]
Maybe War would also make them unelectable / have an election attempt fail? Could be a bit stronger

**Comment by McTsts** [comment]
Pestilence: Block ability
Famine: Disguised as a Horseman
War: No Vote (+Unelectable?)
Death: Delayed Death

No vote and disguise are quite a bit weaker than the other two (though they dont need to all have the same power level)

**Comment by McTsts** [comment]
I prefer the current scheme to, just wanted to give some alternative suggestions in case anyone has a problem with this one, since we usually only do two word names.

**Comment by McTsts** [comment]
>  **shapechange**: it just makes the most sense tbh

Let's keep it like this then. What do you think about maybe giving War something like making the person (secretly?) unelectable? Seems a bit more useful than just taking the vote.

**Comment by McTsts** [comment]
Huh, I think that's actually a good idea. It's a very weak role right now, though the change may almost make it too powerful.

**Comment by McTsts** [comment]
That deserves its own post.

**Comment by McTsts** [comment]
I think with the way we are explaining Horseman what would make the most sense is to take both the vote and make them unelectable - the person just doesnt have time to run for office or vote because of War.

**Comment by McTsts** [comment]
>  **shapechange**: plus yeah. let's be real sab does Jack Shit

Make a post for it :)

**Comment by McTsts** [comment]
Updated description:

**Horseman of War** | Solo Power - Horsemen Team
__Basics__
Each night, the Horseman of War may doom a player. During war their is no time for elections, thus during the next day they will lose their vote and cannot be elected.
__Details__
Dooming a player is an immediate effect. The public vote of players doomed by the Horseman of War will not count during the next day, and should they be elected, the election fails and nobody is elected instead.
When the Horseman of War attempts to doom another Horseman it fails and the two Horsemen unite, joining a shared channel. Doomed players are informed that they have been doomed, but not which Horseman doomed them.
When all remaining Horseman are united and all remaining players doomed, Doomsday is unleashed. Once that happens, the Horseman of War turns into an Apocalyptic Horseman, with the ability to kill a player each night. The Horsemen win when everyone else is dead.

__Simplified__
Each night, the Horseman of War may doom a player, removing their public vote and making them unelectable for a day. If they attempt to doom another Horseman they instead join a shared channel. When all players are doomed, each Horseman may kill a player every night. The Horsemen win if everyone else is dead.

**Comment by McTsts** [comment]
I already noticed but I dont have a thing to send edits from github to discord yet <:pensivebread:800001047966908426>
You can make the post another time :)

**Comment by McTsts** [comment]
I already have 24 open posts it looks bad

**Comment by ThomasRubycrust** [comment]
**Horseman of Death** | Solo Killing - Horsemen Team
__Basics__
Each night, the Horseman of Death may doom a player. The Horseman marks the player, and they will die the next night.
__Details__
Dooming a player is an immediate effect. Players doomed by the Horseman of Death will die at the end of the next night (not an attack).
When the Horseman of Death attempts to doom another Horseman it fails and the two Horsemen unite, joining a shared channel. Doomed players are informed that they have been doomed, but not which Horseman doomed them.
When all remaining Horseman are united and all remaining players doomed, Doomsday is unleashed. Once that happens, the Horseman of Death turns into an Apocalyptic Horseman, with the ability to kill a player each night. The Horsemen win when everyone else is dead.

__Simplified__
Each night, the Horseman of Death may doom a player, killing that player in the next night. If they attempt to doom another Horseman they instead join a shared channel. When all players are doomed, each Horseman may kill a player every night. The Horsemen win when everyone else is dead.

**Comment by ThomasRubycrust** [comment]
**Horseman of Famine** | Solo Power - Horsemen Team
__Basics__
Each night, the Horseman of Famine may doom a player. Doomed by the Horseman of Famine, they are starved, becoming unrecognizable. Instead, they will be seen as a Horseman.
__Details__
Dooming a player is an immediate effect. Players doomed by the Horseman of Famine will permanently be strongly disguised as an arbitrary in-play Horseman role.
When the Horseman of Famine attempts to doom another Horseman it fails and the two Horsemen unite, joining a shared channel. Doomed players are informed that they have been doomed, but not which Horseman doomed them.
When all remaining Horseman are united and all remaining players doomed, Doomsday is unleashed. Once that happens, the Horseman of Famine turns into an Apocalyptic Horseman, with the ability to kill a player each night. The Horsemen win when everyone else is dead.

__Simplified__
Each night, the Horseman of Famine may doom a player, disguising them as a Horseman. If they attempt to doom another Horseman they instead join a shared channel. When all players are doomed, each Horseman may kill a player every night. The Horsemen win when everyone else is dead.

**Comment by McTsts** [comment]
If Pestilence blocks the ability, how does that work if both are immediate night abilities. Are people that use it before being doomed just lucky? Also people aren't told how they are doomed so how would blocking even work.

**Comment by McTsts** [comment]
**Horseman of Pestilence** | Solo Power - Horsemen Team
__Basics__
Each night, the Horseman of Pestilence may doom a player. To sick to act, that any attempt of that player to use an ability during the night will fail
__Details__
Dooming a player is an immediate effect. For the rest of the night, any attempts to use an ability will fail for that player. For some abilities, this may be indistinguishable from other failures (attacks), while others have no other way of failing (investigations).
When the Horseman of Pestilence attempts to doom another Horseman it fails and the two Horsemen unite, joining a shared channel. Doomed players are informed that they have been doomed, but not which Horseman doomed them.
When all remaining Horseman are united and all remaining players doomed, Doomsday is unleashed. Once that happens, the Horseman of Pestilence turns into an Apocalyptic Horseman, with the ability to kill a player each night. The Horsemen win when everyone else is dead.

__Simplified__
Each night, the Horseman of Pestilence may doom a player, blocking their ability for the night. If they attempt to doom another Horseman they instead join a shared channel. When all players are doomed, each Horseman may kill a player every night. The Horsemen win when everyone else is dead.

**Comment by McTsts** [comment]
Now Pestilence, Death and War are all an effect that are temporary and only Famine is permanent. Is that good?

Also, can doomed players be doomed again? I'd say yes, because the Horseman don't necessarily know who's doomed.

**Comment by McTsts** [comment]
>  **shapechange**:
>
> have it be an end night ability and block for the next two phases

I don't think end night works to be honest, because all the other dooming is immediate and it being immediate is fairly relevant because of uniting. Though it should probably be the remainder of the night and the next day.

**Comment by McTsts** [comment]
>  **shapechange**:
> 
> wrong too in basics

Fixed, thanks

**Comment by McTsts** [comment]
And here's Apocalyptic Horseman:

**Apocalyptic Horseman** | Solo Killing - Horsemen Team
__Basics__
Each night, the Apocalyptic Horseman may attack a player. The Horsemen win when everyone else is dead.
__Details__
When all remaining Horsemen are united and all remaining players doomed, Doomsday is unleashed, and all Horsemen turn into an Apocalyptic Horseman.
Attacking a player is an end-night ability.

__Simplified__
Each night, the Apocalyptic Horseman may attack a player. The Horsemen win when everyone else is dead.
The Horsemen turn into Apocalyptic Horsemen, when they have doomed all players.

**Comment by McTsts** [comment]
Also, I added a plain Horseman earlier so that role lists can contain just "Horseman" or "SP", not fully sure it's necessary, but it's probably good. (not really any way around Horseman of Death being SK)

**Horseman** | Solo Power - Horsemen Team
__Basics__
At the end of Day 0, the Horseman becomes one of the other Horseman roles.
__Details__
The Horseman can not immediately become an Apocalyptic Horseman.
Each Horseman can doom a player every night, the effect of which depends on the type of Horseman.
When a Horseman attempts to doom another Horseman it fails and the two Horsemen unite, joining a shared channel. Doomed players are informed that they have been doomed, but not which Horseman doomed them.
When all remaining Horsemen are united and all remaining players doomed, Doomsday is unleashed. Once that happens, all Horsemen turn into Apocalyptic Horsemen, with the ability to kill a player each night. The Horsemen win when everyone else is dead.

__Simplified__
At the end of Day 0, the Horseman becomes one of the other Horseman roles.

**Comment by McTsts** [comment]
I think the PR should be finished for now. I think I like the idea for this quite a bit more than my Ice Royals suggestion. This seems quite a bit more unique and interesting.

**Comment by McTsts** [comment]
**Summary**
The Horsemen Team is a revamped version of the Four Horsemen role which got removed from the role book in v1 of the WWR Role Book. 

The new version of the Horsemen Team consists of four different Horseman roles. The Horsemen do not know each other, and each Horseman has the ability to "doom" a player every night. When a Horseman dooms another Horseman, they "unite", joining a shared channel, but keeping their powers. When all remaining players have been doomed, the Horseman turn into Apocalyptic Horseman, each with the ability to kill a player. The Horsemen win when everyone is dead.

The four horseman roles each have a power that comes with their dooming:
Horseman of Pestilence - Makes the player too sick to act, thus they will be unable to use their action for the remainder of the night and the following day
Horseman of Famine - Starvation makes the player unrecognizable, permanently and strongly disguising them as an arbitrary Horseman
Horseman of War - There is no time for elections during war, thus the player's vote will not count during the next day, and should they be elected the election will fail
Horseman of Death - This Horseman marks the player and they will die at the end of the next night

FAQ
Q: Why not an instant win when everyone is doomed? 
A: It's intended for there to be more Horseman than there would be of other solo roles, so the win condition is quite a bit harder. Exact details may need balancing.

Q: Role Blocking is bad. 
A: I also agree, but I also think role-changing is bad, but Vampire is still valid. Things like this are fine when used in moderation and kept to solo teams that have it built in from the start in my opinion. I think by having it a very limited thing exclusive to 1/4th of a solo team it's fine, but it's nothing I would want to see added to town/wolves or an existing solo team.

Q: Is uniting too difficult?
A: Possibly, the original Horseman got a list of 5 players, one of which was guaranteed to be a Horseman to make uniting easier. But they also only got one action per night collectively (so one action every 4th night for each horseman) so I don't know. 

Q: Do players know they're doomed?
A: They will be informed they have been doomed (like sleepless), but not by which Horseman, thus they do not know by which power they are affected.

**Review by cryptidjayden — APPROVED** [review]

**Comment by ThomasRubycrust** [comment]
This is I think the most complicated suggestion. Check the pinned messages for a summary as well as a link to the PR. The suggestion is an in my opinion really unique solo team. I closed the Ice Royals suggestion because this team also has voting manipulation on one role and seems more interesting overall.

❌ Reject
✅ Approve

**Pull request merged**
