### PR TITLE
Readd Jack Robinson and Robin Jackson

### PR DESCRIPTION
**Pull request by McTsts**
this is a PR to add these two roles

### CODE REVIEW

**Comment by venomousbirds** [comment]
I hate this fucking family

**Comment by McTsts** [comment]
what's the problem? :(

**Comment by venomousbirds** [comment]
Is not adding them gonna make you cry?

**Comment by McTsts** [comment]
Yes.

**Comment by McTsts** [comment]
Just read their descriptions, they're so good!!!!11!!

**Comment by venomousbirds** [comment]
Then cry.

**Comment by McTsts** [comment]
That's so rude.

**Comment by venomousbirds** [comment]
Yeah that's the point.

**Comment by McTsts** [comment]
wow

**Pull request closed without merging**
