### PR TITLE
Create blessed wolf

### PR DESCRIPTION
**Pull request by McTsts**
this is a role from the old role book, with the modification that the attacker learns why they escaped. (Sacred Wolf was nerfed and became Scared Wolf) Haven't thought about it too much but I'm not sure why it got removed (yes, it's stronger than a Scared Wolf, but most of the wolves usually die during the day anyway)

### CODE REVIEW

**Comment by cryptidjayden** [comment]
sounds good

**Review by venomousbirds — APPROVED** [review]
it's probably a good role to put in a smaller game, to give the wolf team a little more of an advantage. Give a good variety in wolfpack roles too

**Comment by McTsts** [comment]
I'm honestly not sure if this one is actually much stronger than Scared Wolf, since I added the Runner-like thing. (the original Sacred Wolf was just that it escapes any attacks), but I think the change makes it more balanced

**Comment by McTsts** [comment]
If anyone has any opinion on if just escaping (without being revealed) or my version is better let me know :)

**Comment by Shepherdwhen** [comment]
For a prospective name change what about "alert wolf", because sounds too much like scared wolf

**Comment by Shepherdwhen** [comment]
also what about not the role that attacked it but the alignment, so it distinguishes between solo and town or would that be too weak, I think it's a little bit better than scared but not too strong that wolves use it to work out what TK is

**Comment by McTsts** [comment]
Or more fittingly: "Immune Wolf" or something similiar to that

**Comment by McTsts** [comment]
> also what about not the role that attacked it but the alignment, so it distinguishes between solo and town or would that be too weak, I think it's a little bit better than scared but not too strong that wolves use it to work out what TK is

Is that a reply to something? The idea seems decent, but I don't really think it fits the role.

**Comment by Shepherdwhen** [comment]
Immune would suggest it is immune to all kills not just the one, alert implies that it escapes and then sees who/what/how it was attacked


> > also what about not the role that attacked it but the alignment, so it distinguishes between solo and town or would that be too weak, I think it's a little bit better than scared but not too strong that wolves use it to work out what TK is
> 
> Is that a reply to something? The idea seems decent, but I don't really think it fits the role.

Just a thought I had because the origional said it was removed, I thought it was removed because it was abused to find TK

**Comment by McTsts** [comment]
I think you misread the role 
hepi

**Comment by Shepherdwhen** [comment]
Oh, yep I'm dumb I thought It was told what attacked it and escaped 1 attack but it's escapes all attacks but attacker knows they are sacred wolf

**Comment by McTsts** [comment]
Renamed to avoid confusion

**Comment by McTsts** [comment]
This role wins the award for most disliked role suggestion 👍

**Comment by McTsts** [comment]
I also voted against this role lmao

**Pull request closed without merging**
