### PR TITLE
1029  flute app and horseman and coroner to misc

### PR DESCRIPTION
**Pull request by 12Metatron**
if i missed any files that need to be changed, let me know

### CODE REVIEW

**Review by rupertandrosy — APPROVED** [review]

**Comment by rupertandrosy** [comment]
ive just realised i dont know how to move a file from one folder to another so @McTsts or someone can do coroner instead

**Comment by rupertandrosy** [comment]
fixes #1029

**Comment by 12Metatron** [comment]
haha sorry i dont know how i named it flute player instead of flute apprentice. thanks for catching it

**Review by McTsts — APPROVED** [review]

**Comment by McTsts** [comment]
There we go, rebased to v16

**Pull request merged**
