### PR TITLE
Update flute player

### LINKED ISSUE #109: FP Balance Change
I suggest that a single flute player can enchant Round(n/10) players and several flute players can each enchant Round(n/20) players

### PR DESCRIPTION
**Pull request by McTsts**
not sure if the wording on this is particularly good
Fixes #109

### CODE REVIEW

**Comment by Mjnstag** [comment]
idk if its better, but maybe move "The number of enchants per night does not change throughout the game." after the second sentence explaining >1 FP since it may be interpreted as that >1 FP amount of enchants may change during the game?

**Comment by McTsts** [comment]
I see the issue you mean, and that should be changed, but I don't understand how exactly you suggest to fix it.

**Comment by Mjnstag** [comment]
probably moving "The number of enchants per night does not change throughout the game." to a new line after both sentences explaining the amount of enchants

**Comment by Shepherdwhen** [comment]
Does that line mean that 3 flute players could enchant 3 people with 20 players?

**Comment by Mjnstag** [comment]
yea, think so

**Comment by Shepherdwhen** [comment]
So flute players gain an enchant to (number of players/10 rounded) and one for each flute player over (number of players/10)

**Comment by McTsts** [comment]
> probably moving "The number of enchants per night does not change throughout the game." to a new line after both sentences explaining the amount of enchants

Thing is... It can if the amount of FP's changes

**Comment by venomousbirds** [comment]
All this changes is that enchants are based on player amount, and not on fluteplayer amount, right?

**Comment by McTsts** [comment]
No, it's based on both. n/10 for 1 FP and n/20 for 2 FP. We can't merge this yet though because it's worded badly.

**Pull request merged**
