### PR TITLE
IW failure on hit packless werewolf

### LINKED ISSUE #427: IW => Packless Werewolf
suggested special case for IW if hit packless wolf: nothing happens (useful for IW=>Imp)

### PR DESCRIPTION
**Pull request by McTsts**
Fixes #427

This is useful in general but particularly for IW => Imp

### CODE REVIEW

**Comment by Shepherdwhen** [comment]
would #436  have this as part of it too?

**Review by venomousbirds — COMMENTED** [review]
Would make Infecting Wolf even more careful, not sure if that's what we wanna go for but I don't dislike the change

**Comment by McTsts** [comment]
> Would make Infecting Wolf even more careful, not sure if that's what we wanna go for but I don't dislike the change
No, I'd consider this a buff. Turning a non-pack wolf into a wolf is not an advantage. With this the Infecting Wolf will know they have hit the non-pack wolf and will be able to contact them.

**Review by venomousbirds — APPROVED** [review]
Didn't think about it like that

**Pull request merged**
