### PR TITLE
Add Pack Warlock

### PR DESCRIPTION
**Pull request by venomousbirds**
doing it right this time

### CODE REVIEW

**Comment by venomousbirds** [comment]
fixes #412

**Review by McTsts — APPROVED** [review]

**Comment by ThomasRubycrust** [comment]
Do we want to continue discussing this role or are we dropping it? I'm not sure if the impact on balancing would really be a problem, presumably the PWa would start out being unable to check and then only get a check in the second night of being PW.

**Comment by venomousbirds** [comment]
This was mostly meant as a transformation role like Trickster Wolf, a solution so Lwa doesn't have to turn into a lycan

**Comment by ThomasRubycrust** [comment]
In the issue attached to this Jay brought up that they thought it would be bad because it would remove a key role for smaller games, which is what put this role on hold for now.

**Comment by venomousbirds** [comment]
Little confused by what "it would remove a key role for smaller games" means, where did Jay say this? So I can read it back

**Comment by ThomasRubycrust** [comment]
#412

**Comment by ThomasRubycrust** [comment]
> I understand the whole 'why would a warlock turn into a wolf lol' jig, but I think the role is fine as it is, to be honest. It's a really easy way to give wolves a balanced investigative especially in smaller games where pack might suffer from thinner ranks. The proposed Pack Warlock change would make it much more powerful and would remove what I believe to be a key role for smaller games. There is some current overlap with CF, but CF is imo quite a bit stronger, and so if LW was changed in this, there'd still be that gap. PsyW is meanwhile much weaker.
> 
> Ultimately, names are just names - do they really have to make sense down to the tiniest detail?

**Comment by venomousbirds** [comment]
I still have no clue what "would remove what I believe to be a key role for smaller games" means in this context. Pack warlock is here to give consistency not because of name specifically but to keep Lone Warlock non-lycan. Lone Warlock isn't as strong as normal Warlock, it's only one check every 2 nights

**Comment by ThomasRubycrust** [comment]
I'm also not very convinced that CF is much stronger and PsyW is much weaker. I think LWa as it is can actually be a bit too weak if wolves get unlucky and if they get lucky its more of a warlock. The PWa change would actually make the role a bit more consistent.

**Comment by ThomasRubycrust** [comment]
Rejected by vote

**Pull request closed without merging**
