### PR TITLE
Create shepherd

### PR DESCRIPTION
**Pull request by Shepherdwhen**

### CODE REVIEW

**Comment by McTsts** [comment]
moved to correct location

**Review by McTsts — CHANGES_REQUESTED** [review]
role is empty

**Comment by Shepherdwhen** [comment]
Did I fix it

**Comment by McTsts** [comment]
> Did I fix it

Yes

**Review by McTsts — CHANGES_REQUESTED** [review]
This PR should probably also include that other role from the flock team

**Comment by Shepherdwhen** [comment]
> This PR should probably also include that other role from the flock team

Done :D

**Comment by McTsts** [comment]
Split Herding Dog into a separate role & did style changes.

**Review by McTsts — APPROVED** [review]
seems good

**Review by venomousbirds — APPROVED** [review]
Looks good, we already have it on mini wolves anyway. Should stay limited for now

**Comment by McTsts** [comment]
<@&584767449078169601> I'll merge this one tomorrow unless anyone else has a review.

**Comment by cryptidjayden** [comment]
seems simultaneously overpowered and impossible to win as.

**Comment by cryptidjayden** [comment]
if you guys like it, go ahead. but honestly i really don't see it working.

**Comment by venomousbirds** [comment]
Elaborate plz

**Comment by McTsts** [comment]
I don't think this will be impossible to win as. It's basically a weaker Flute Player, but with additional Devil-like powers. The removal of the 2nd player per night doesn't seem like a huge issue imo since the Devil-like powers make up for it.

**Review by Mjnstag — APPROVED** [review]
i dont know how well it will work, but im up for trying it out

**Comment by McTsts** [comment]
@cryptidjayden could you please elaborate?

**Pull request merged**
