### PR TITLE
Create Poisoner

### PR DESCRIPTION
**Pull request by bobloy**
A werewolf role that can beat protection roles, but choreographs the target

### CODE REVIEW

**Comment by Shepherdwhen** [comment]
Roleblocking roles are a sin in wwr

just saying

**Comment by bobloy** [comment]
Removing the "can't take an action" part still leaves a perfectly acceptable role IMO, if necessary.

**Comment by McTsts** [comment]
I thinking disabling a passive protective ability is acceptable. I'd be against disabling active protections or blocking active powers. I think this would work as a role, though it would probably be a rather rare one.

**Comment by Shepherdwhen** [comment]
would this include devil/demon protection? that passively activates on attack

**Comment by bobloy** [comment]
It would be easy enough to say it works on town roles only to avoid devil/demon stuff.

**Comment by bobloy** [comment]
Further, if its only town roles, I could even list all the roles it works on.

Runner
Acrobat
Macho
Cursed Civilian

**Comment by McTsts** [comment]
I like to avoid lists of roles because they're not very future proof and we have a high chance of forgetting to update them. E.g. if/once we add Idiot it would need to be added to this list. I think just saying it only affects town roles (or maybe town and wolf roles?) would be best. Maybe it should also have some mechanic like Tanner that gives it a bit of a chance to find the wolfpack

> If the tanner disguises a player who is part of the wolfpack, the tanner is informed by the Hosts that “At least one of the players you tanned today is part of the wolfpack”.

**Comment by Shepherdwhen** [comment]
idiot too

**Comment by bobloy** [comment]
> I like to avoid lists of roles because they're not very future proof and we have a high chance of forgetting to update them. E.g. if/once we add Idiot it would need to be added to this list. I think just saying it only affects town roles (or maybe town and wolf roles?) would be best. Maybe it should also have some mechanic like Tanner that gives it a bit of a chance to find the wolfpack

Either town/wolf roles only, or because this wording is used:
`If the Devil is attacked while a soul is in the pool, a soul will automatically be used to protect the Devil. `
It implies it not passive, but a triggered active ability.

**Comment by McTsts** [comment]
It's probably best to just say it only affects town/werewolf roles

**Comment by McTsts** [comment]
Maybe this should be a day ability that affects the next night instead? Seems like that'd make more sense

**Comment by bobloy** [comment]
> Maybe this should be a day ability that affects the next night instead? Seems like that'd make more sense

That would buff them, allowing a night 1 poison. This prevents anyone from being weakened until night 2

**Comment by McTsts** [comment]
This role received controversial responses due to it being sort of like role blocking. No conclusion has been reached for v13.

**Comment by venomousbirds** [comment]
I dislike the role blocking part, and completely disabling those abilities just takes away from those roles. People would not like playing a game with this role, I think

**Comment by bobloy** [comment]
I think this roles adds a lot more interesting gameplay. If I were macho and I were poisoned, I'd have to decide whether to reveal that I was poisoned or not, betting whether the poisoner has found the wolves.

This could also lead to wolves taking a risk and attacking a macho mayor. 

Also, I like to think of roles like these from the perspective of the games they're not in. This role existing allows fake claiming macho to be safer for wolves.

**Comment by McTsts** [comment]
Closing this suggestion due to lack of development on it. Feel free to reopen this (now or at any point in the future) if you want to further discuss/develop this idea.

**Pull request closed without merging**
