### PR TITLE
Create golem

### PR DESCRIPTION
**Pull request by ThomasRubycrust**
Implements #324

### CODE REVIEW

**Comment by venomousbirds** [comment]
I haven't even seen this role before, but I really like the idea of an ua for every election. Problem is that Guardian doesn't happen much so it's another role that is best put in larger games
The nightly ability definitely does help to make it more interesting

**Comment by ThomasRubycrust** [comment]
The rarity of Guardian is why the role suggestion was initially closed. With the nightly ability it should increase the chance of Guardian being able to occur significantly.

**Comment by 12Metatron** [comment]
i like this role, though it probably couldn't be used except in large games. But that's fine in its own way I think.

**Comment by McTsts** [comment]
@venomousbirds why did you mark this as a draft?

**Comment by venomousbirds** [comment]
only a few people commented on it and i don't think its ready yet, feel like new roles will need input from more people if they're completely new suggestions.

**Comment by McTsts** [comment]
That's what we're doing right now, isn't it?

**Comment by venomousbirds** [comment]
its been up for more than a month and there's been plenty of people commenting on other PRs at the time

**Comment by venomousbirds** [comment]
hm fair i just thought it wouldnt be worth it to work on, at least for this role book, because i havent seen much activity on it

**Review by venomousbirds — APPROVED** [review]

**Pull request merged**
