### PR TITLE
Simplified Description

### PR DESCRIPTION
**Pull request by ThomasRubycrust**
So here's an example of a simplified description. I think it covers pretty much everything a person looking up CF would want to know.

### CODE REVIEW

**Comment by venomousbirds** [comment]
just the simplified part or the whole description?

**Comment by venomousbirds** [comment]
oh okay thats convenient
 so whats the deleted line for

**Comment by venomousbirds** [comment]
simplified description looks good

**Comment by venomousbirds** [comment]
do we need to this this to EVERY role tho i will cry

**Comment by venomousbirds** [comment]
allright, i'll start with ua

**Comment by venomousbirds** [comment]
everything on this branch? and does it need to be added to the role or is it a new role?

**Comment by ThomasRubycrust** [comment]
Admittidely most WI's (except CF) were already pretty good to begin with. Yes, all in this branch. Add it to the end of the role with a newline inbetween like I did.

**Comment by ThomasRubycrust** [comment]
and the `__Simplified__` header, I'll have it split the role on that

**Comment by ThomasRubycrust** [comment]
> should i do the cupid variants? most people only find them via the cupid alignments command anyways

I think its probably best if every role has it

**Comment by ThomasRubycrust** [comment]
Wolves are done, I'll do TG and TI now.

**Comment by ThomasRubycrust** [comment]
Uh, good luck, that may be the hardest category.

**Comment by ThomasRubycrust** [comment]
Town is done. Elected now.

**Comment by venomousbirds** [comment]
Limited roles also?

**Comment by venomousbirds** [comment]
non-limited solos are done

**Comment by ThomasRubycrust** [comment]
> Limited roles also?

Yes

**Comment by ThomasRubycrust** [comment]
I think that's all we're missing now

**Comment by ThomasRubycrust** [comment]
I WROTE CULT LEMBER???? (instead of leader)

**Comment by ThomasRubycrust** [comment]
I believe that's all. We'll need to review this and I need to adjust some code before we merge it.

**Comment by ThomasRubycrust** [comment]
Just read through all of them again, and did some changes.

**Pull request merged**
