### PR TITLE
Wager: Allow changing attack target

### LINKED ISSUE #611: Wager change
> devils wager: we should do is add a thing that wager recipient can change, but cant have their soul back

@McTsts

### PR DESCRIPTION
**Pull request by ThomasRubycrust**
Fixes #611

### CODE REVIEW

**Comment by ThomasRubycrust** [comment]
Added that, I left it out initially, because I want to avoid adding even more text, but turns out it doesnt require many words.

**Review by cryptidjayden — APPROVED** [review]
change the however in line 18 to a but, good change

**Comment by cryptidjayden** [comment]
fuck yeah my github skills are fucking elite

**Comment by venomousbirds** [comment]
pro gamer move right there

**Pull request merged**
