### PR TITLE
Devil cant be wager killed

### LINKED ISSUE #36: Devil: wager kill the devil
"Using the wager to attack the Devil always fails."

Maybe we should add something to clarify that when a wager is used to kill the devil that the devil wont have an increase in souls like when attacking another player since the soul is immediately used to protect the devil.

### PR DESCRIPTION
**Pull request by McTsts**
Fixes #36

### CODE REVIEW

**Comment by Mjnstag** [comment]
maybe better to also mention that the devil will (not) gain a soul since that might be vague from that change?

**Review by Mjnstag — CHANGES_REQUESTED** [review]
maybe better to also mention that the devil will (not) gain a soul since that might be vague from that change?

**Review by venomousbirds — CHANGES_REQUESTED** [review]
It currently seems like the attack on the devil fails but the devil still gains a soul, I don't know how to word it better but right now it's worded even weirder

**Comment by Mjnstag** [comment]
maybe something like:
"Using the wager to attack the Devil will fail end-night, but the Devil will still gain a soul."

or:
"Using the wager to attack the Devil will fail end-night, but the Devil will still gain the sold soul."

or:
"Using the wager to attack the Devil will fail end-night, but the sold soul will be used to protect the Devil."

**Comment by venomousbirds** [comment]
Last option is the only option that actually clarifies that the sold soul is not added to the current Devil souls

**Comment by McTsts** [comment]
The sold soul **is** added to the Devils total.

**Comment by venomousbirds** [comment]
It's added and removed. Right now it sounds like it's not removed

**Comment by McTsts** [comment]
It is **not** removed.

**Comment by McTsts** [comment]
Once the soul is sold, the wager's recipient no longer has anything to do with anything that happens. The Devil executes the devil's wager attack. The Devil will not attack themself. The Devil gains the soul from the wager and just doesn't do the attack.

**Comment by venomousbirds** [comment]
Makes sense in that case, I just remember some discussion that the soul gaining specifically shouldn't be added for some reason

**Comment by McTsts** [comment]
@venomousbirds @Mjnstag I've changed it and it should be clearer now.

**Review by venomousbirds — APPROVED** [review]

**Review by Mjnstag — APPROVED** [review]

**Pull request merged**
