### PR TITLE
Create Tracking Wolf

### PR DESCRIPTION
**Pull request by Shepherdwhen**
A new pack WI idea, can't think of a name rn which is why it's called "? Wolf"

### CODE REVIEW

**Comment by Shepherdwhen** [comment]
It was just a basic draft but yeah I agree with these changes

**Comment by McTsts** [comment]
Overall I think the idea could work. It's similar to AT, but also unique enough. I don't think it would be overpowered because categories aren't always enough info (a Huntress and Assassin would be treated very differently. Bard/Bartender and Citizen are completely different levels of strength), but still, it's enough info to be very useful.

**Comment by McTsts** [comment]
Rewrote the role according to my feedback.

**Comment by ThomasRubycrust** [comment]
@Shepherdwhen check the new description at some point when you have time, and let me know what you think.

**Comment by Shepherdwhen** [comment]
The new changes seem fine, for the name Stalking/Stalker Wolf would work if we didn't already have a town role called stalker

**Comment by ThomasRubycrust** [comment]
We'll never add Stalker Wolf, but I still don't think it's a role name we can use.

**Comment by cryptidjayden** [comment]
i like this! can't think of a name, though, which is a shame bc stalker would fit so well.

**Comment by McTsts** [comment]
I'm kinda opposed to just removing Stalker, but I think renaming this one to Stalker Wolf and revamping Stalker under a new name is fine, and Stalker is very rarely used (last used 22 games ago, only a total of 3 uses on WWR) so it probably wouldn't be too confusing.

**Comment by cryptidjayden** [comment]
i'd be fine with that tbh

**Comment by cryptidjayden** [comment]
gonna link back to #599 to discuss the stalker thing more bc i had another thought

**Comment by venomousbirds** [comment]
i dislike this, i think its a really weird an unneccesary check

**Comment by venomousbirds** [comment]
clarification on my comment earlier

the check is unusual and unneccesary, it just adds another weird check mechanic to the game and i dont think we need that. 
all the kinds of threats are just a little vague and i think it will add more confusion than clarification. overall i think this is a pretty bad WI and it won't help much
also i dont think stalker wolf makes sense as a name. no need to delete another role for a role draft.

**Comment by ThomasRubycrust** [comment]
The check works the same way as the AT check

**Comment by Shepherdwhen** [comment]
Also the Check isn't confusing, the higher the threat the more rewarding it is to have that player dead most of the time

**Comment by Shepherdwhen** [comment]
The only time it isn't is weird edgecases

**Comment by venomousbirds** [comment]
no this check has more than the AT check and i dislike that, it only complicates the game

>Check isn't confusing

i find it to be confusing, its put weirdly imo

**Comment by venomousbirds** [comment]
its a big bundle of words, i think putting it like the first commit (new line for every sort of check) would make it more clear

**Comment by ThomasRubycrust** [comment]
Honestly, I find this much much more readable than the initial more table like list.

**Comment by Shepherdwhen** [comment]
> Honestly, I find this much much more readable than the initial more table like list.

I personally find both readable but the current one fits the consistency of other roles

**Comment by cryptidjayden** [comment]
i like the role! i like the more dynamic threat interactions and i feel pack could really benefit from a WI that is (imo) stronger than PsyW. i also saw vera's point about the mildly confusing bundle of words; to fix this, i made sure each scenario was phrased in the same way, which i hope helps. (i also changed the last line to be consistent with aura teller.)

a thought: should we implement the different threat levels with aura teller? it runs the risk of making AT more/too powerful, but could add more interest to what is (imo) a more "boring" role than many of the other TIs. it'd also help differentiate from huntsman somewhat. if anyone wants to expand on this further, a new issue or PR could be created.

**Comment by McTsts** [comment]
I think the phrasing is now better. I don't think AT should be changed.

**Comment by Shepherdwhen** [comment]
we could also call this role prowler wolf/hunting wolf/tracker wolf if we're not removing stalker

**Comment by McTsts** [comment]
I think those honestly make more sense than Stalker Wolf? Those seem more like things a wolf would actually do.

**Comment by venomousbirds** [comment]
I think Tracker Wolf fits best out of those

**Comment by McTsts** [comment]
Updated role to `Tracker Wolf`

**Comment by venomousbirds** [comment]
still dont like it tho, but that name does fits best

**Comment by cryptidjayden** [comment]
i think i prefer prowling to tracker, but either work!

**Comment by venomousbirds** [comment]
Tracking wolf? cuz its also infecting wolf

**Comment by McTsts** [comment]
Tracking Wolf also works, but for Infecting the other option is Infected which doesnt make any sense.

**Comment by venomousbirds** [comment]
true
i do think tracking sounds a little better than tracker

**Review by ThomasRubycrust — APPROVED** [review]

**Review by venomousbirds — APPROVED** [review]

**Pull request merged**
