### PR TITLE
Remove Apprentice

### PR DESCRIPTION
**Pull request by McTsts**
This role has *never* been used. I don't think we are very likely to use it, so there's no reason it should remain in the role book.

### CODE REVIEW

**Comment by McTsts** [comment]
@venomousbirds wants to try this role in a game at some point

**Comment by McTsts** [comment]
We still have not used this.

**Comment by Shepherdwhen** [comment]
> We still have not used this.

S7G6 used it idk how effective it was but it was still used

**Comment by McTsts** [comment]
Oh huh, that was before I opened this the first time. Weird that I didnt find that usage of the role.

**Pull request closed without merging**
