### PR TITLE
Create idiot

### PR DESCRIPTION
**Pull request by McTsts**
idiot

### CODE REVIEW

**Comment by venomousbirds** [comment]
idiot

**Comment by Mjnstag** [comment]
idiot
if you add this, maybe it would be a good idea to note the way the role works (after losing a vote) in relation to vote stealing roles.

**Comment by venomousbirds** [comment]
I still think idiot should be told when their vote is taken away

**Comment by McTsts** [comment]
> I still think idiot should be told when their vote is taken away

I already added that.

**Comment by McTsts** [comment]
> idiot
> if you add this, maybe it would be a good idea to note the way the role works (after losing a vote) in relation to vote stealing roles.

Good point.

**Comment by venomousbirds** [comment]
> > I still think idiot should be told when their vote is taken away
> 
> I already added that.

Oops, I thought you just added the old idiot description that didn't inform the vote being taken away

**Comment by McTsts** [comment]
> > > I still think idiot should be told when their vote is taken away
> > 
> > 
> > I already added that.
> 
> Oops, I thought you just added the old idiot description that didn't inform the vote being taken away

Nope, this one is changed a bit.

**Comment by bobloy** [comment]
Does an idiot mayor have zero votes or one vote? Mayor grants an "extra vote"

**Comment by McTsts** [comment]
> Does an idiot mayor have zero votes or one vote? Mayor grants an "extra vote"

Interesting question. From a bot functionality perspective we'd have to decide between it having the extra vote (the Mayor vote always adds +1 or -1 votes to your vote value) or the attacked Idiot not having access to #voting-booth (which would reveal them as attacked idiot)

**Comment by Shepherdwhen** [comment]
> > Does an idiot mayor have zero votes or one vote? Mayor grants an "extra vote"
> 
> Interesting question. From a bot functionality perspective we'd have to decide between it having the extra vote (the Mayor vote always adds +1 or -1 votes to your vote value) or the attacked Idiot not having access to #voting-booth (which would reveal them as attacked idiot)

What if we made an identical mayor role that just doesn't have an extra vote or is that a dumb fix?

**Comment by McTsts** [comment]
> > > Does an idiot mayor have zero votes or one vote? Mayor grants an "extra vote"
> > 
> > 
> > Interesting question. From a bot functionality perspective we'd have to decide between it having the extra vote (the Mayor vote always adds +1 or -1 votes to your vote value) or the attacked Idiot not having access to #voting-booth (which would reveal them as attacked idiot)
> 
> What if we made an identical mayor role that just doesn't have an extra vote or is that a dumb fix?

It's still possible to figure out the difference from those roles

**Comment by Shepherdwhen** [comment]
> > > > Does an idiot mayor have zero votes or one vote? Mayor grants an "extra vote"
> > > 
> > > 
> > > Interesting question. From a bot functionality perspective we'd have to decide between it having the extra vote (the Mayor vote always adds +1 or -1 votes to your vote value) or the attacked Idiot not having access to #voting-booth (which would reveal them as attacked idiot)
> > 
> > 
> > What if we made an identical mayor role that just doesn't have an extra vote or is that a dumb fix?
> 
> It's still possible to figure out the difference from those roles

Oh yeah, tbh the only real way would be +1 vote, orrrrr a change in mayor so that if a mayor player is idiot they get +0 once attacked or or when you use the command to remove vote power you remove 2 and then mayor fills the gap of the -1 vote making it 0

**Comment by McTsts** [comment]
> > > > > Does an idiot mayor have zero votes or one vote? Mayor grants an "extra vote"
> > > > 
> > > > 
> > > > Interesting question. From a bot functionality perspective we'd have to decide between it having the extra vote (the Mayor vote always adds +1 or -1 votes to your vote value) or the attacked Idiot not having access to #voting-booth (which would reveal them as attacked idiot)
> > > 
> > > 
> > > What if we made an identical mayor role that just doesn't have an extra vote or is that a dumb fix?
> > 
> > 
> > It's still possible to figure out the difference from those roles
> 
> Oh yeah, tbh the only real way would be +1 vote, orrrrr a change in mayor so that if a mayor player is idiot they get +0 once attacked or or when you use the command to remove vote power you remove 2 and then mayor fills the gap of the -1 vote making it 0

if you have -1 votes with mayor it's -2

**Comment by Shepherdwhen** [comment]
> > > > > > Does an idiot mayor have zero votes or one vote? Mayor grants an "extra vote"
> > > > > 
> > > > > 
> > > > > Interesting question. From a bot functionality perspective we'd have to decide between it having the extra vote (the Mayor vote always adds +1 or -1 votes to your vote value) or the attacked Idiot not having access to #voting-booth (which would reveal them as attacked idiot)
> > > > 
> > > > 
> > > > What if we made an identical mayor role that just doesn't have an extra vote or is that a dumb fix?
> > > 
> > > 
> > > It's still possible to figure out the difference from those roles
> > 
> > 
> > Oh yeah, tbh the only real way would be +1 vote, orrrrr a change in mayor so that if a mayor player is idiot they get +0 once attacked or or when you use the command to remove vote power you remove 2 and then mayor fills the gap of the -1 vote making it 0
> 
> if you have -1 votes with mayor it's -2

Oh yeah Idk then mayor + idiot is gonna be weird to do

**Comment by bobloy** [comment]
Sounds like there needs to be a multiplier step for voting power. Idiot would change multiplier from default 1 to 0.

**Comment by Mjnstag** [comment]
what would be the message to wolves/other attackers when the target doesnt die? "nothing happened"?

**Review by venomousbirds — APPROVED** [review]

**Comment by McTsts** [comment]
> what would be the message to wolves/other attackers when the target doesnt die? "nothing happened"?

Yeah, just generic failure, like Devil/Scared Wolf/Redirection/Protected

**Pull request merged**
