### PR TITLE
Shepherd Reaper Edge Case

### PR DESCRIPTION
**Pull request by McTsts**
I'm crying. Please help.

### CODE REVIEW

**Comment by venomousbirds** [comment]
i dont get it

**Comment by McTsts** [comment]
If the Shepherd dies the Reaper gets its power converted to the reapers effect. Usually for roles like FP it is easy and you can replaced "enchanted" with "sleepless". Shepherd has two effects, "tagged" and "herded". This edge cases makes it so by using the Shepherd power the Reaper applies a new effect, "nightmare-tagged" which is the Reaper's equivalent of tagged. If two nighmared-tagged players interact they become nightmared (this is how Shepherd works). The Shepherd has additional poweers such as unherding to steal votes and auto-unherding to escape attacks, the second sentences clarifies that sleepless players can be used in the same way by the Reaper as herded players could be used by the Shepherd. The final sentences adds that nightmared players are informed when they are un-nightmared. This is relevant because unlike herded, nightmared doesn't have a channel, only a message when you get it.

**Comment by venomousbirds** [comment]
maybe only add one shepherd effect, so just tagging to make players sleepless, no need to make it complicated

**Comment by McTsts** [comment]
We can probably do that

**Comment by McTsts** [comment]
PR updated

**Pull request merged**
