### PR TITLE
Shepherd Changes

### LINKED ISSUE #600: Flock Team Kinda Weak + Needs Fixing
We need to decide if Shepherd can gain as many votes as it wants or one a day, the original intention was as many as it wants but that was decided to be too strong, so it was nerfed.

A buff could be that the Herding dog can as an end night ability, herd one tagged player, like how the reaper has a built-in sleepless to guarantee one sleepless a night.

The Shepherd also needs to know who is herded and unherded, for consistency I think the shepherd should learn who is currently herded each phase change/who is newly herded when they get herded.

### PR DESCRIPTION
**Pull request by ThomasRubycrust**
Fixes #600
This isn't complete yet.

### CODE REVIEW

**Comment by venomousbirds** [comment]
until now it looks good

**Comment by McTsts** [comment]
im not sure if its necessary

**Comment by venomousbirds** [comment]
i dont understand or like shepherd so all i can do is correct typos

**Comment by Shepherdwhen** [comment]
> i dont understand or like shepherd so all i can do is correct typos

probably needed I can't fucking spell sometimes

**Comment by McTsts** [comment]
Wouldn't it make more sense when the Shepherd learns whenever someone is herded?

**Comment by Shepherdwhen** [comment]
> Wouldn't it make more sense when the Shepherd learns whenever someone is herded?

That sound better

**Review by McTsts — APPROVED** [review]
I'm not sure if the direct herding power really makes sense, but sure.

**Pull request merged**
