### PR TITLE
Herding Dog Buff

### PR DESCRIPTION
**Pull request by venomousbirds**
Maybe need to add more but this is proposed

### CODE REVIEW

**Comment by Shepherdwhen** [comment]
The thing is Hearding Dog was never intended for a list, it was just in case of a LA on Shepherd, I had thought of buffs however, one being that each night the Hearding Dog visits a player and acts as a faux tag, if a tagged player visits the HD's target, the HD's target is Hearded

**Comment by McTsts** [comment]
> The thing is Hearding Dog was never intended for a list, it was just in case of a LA on Shepherd, I had thought of buffs however, one being that each night the Hearding Dog visits a player and acts as a faux tag, if a tagged player visits the HD's target, the HD's target is Hearded

That's basically #539

**Review by McTsts — APPROVED** [review]

**Comment by Shepherdwhen** [comment]
> > The thing is Hearding Dog was never intended for a list, it was just in case of a LA on Shepherd, I had thought of buffs however, one being that each night the Hearding Dog visits a player and acts as a faux tag, if a tagged player visits the HD's target, the HD's target is Hearded
> 
> That's basically #539

Kinda but instead the visitor is only herded if they're already tagged, and it acts as a temporary tagging to the HD's Target instead

**Comment by Shepherdwhen** [comment]
The other Idea I had is they passively learn the role and name of the visitor who caused the herding, this would also make the HD a Solo Investigative

**Comment by McTsts** [comment]
Investigative is a sub-category of Power and does not necessarily need to exist

**Pull request merged**
