### PR TITLE
Update saboteur wolf

### PR DESCRIPTION
**Pull request by McTsts**

### CODE REVIEW

**Comment by McTsts** [comment]
Updated:

**Saboteur Wolf** | Werewolf Power
__Basics__
Each night, the Saboteur Wolf may select one player to disqualify from the public election poll.
__Details__
Each night, the Saboteur Wolf may select one player. 
That player can still be voted for in the election poll in the following day phase, but should they win, nobody is elected. The selected player can still be lynched and can still vote in the election poll. 
The Saboteur Wolf may not sabotage the same player two nights in a row, but can sabotage themself or others in the wolfpack.
Sabotaging is an immediate ability.

__Simplified__
Each night, the Saboteur Wolf may select one player to disqualify from the next day's public election poll.

**Comment by venomousbirds** [comment]
What exactly sparked this conversation (the need to change Sab Wolf)? I don't mind the change but I'd like to know why changes were requested.

**Comment by McTsts** [comment]
We were discussing Horseman and one of their powers was making something unelectable so this came up, it should be in that PR

**Comment by McTsts** [comment]
**shapechange**:
honestly maybe we should change sab to being secret too? i feel like right now it doesn't have much impact on games

_Originally posted by @CrowdfordBot in https://github.com/McTsts/Werewolves-Roles/issues/772#issuecomment-1269027323_

**Pull request merged**
