### PR TITLE
Remove pyronner

### PR DESCRIPTION
**Pull request by ThomasRubycrust**

### CODE REVIEW

**Comment by venomousbirds** [comment]
wait why would this be removed but scwww stays?

**Comment by McTsts** [comment]
scwww seems slightly more serious, but we can remove both

**Comment by venomousbirds** [comment]
i like both tbh, pyronner could be used in normal games too because a lone pyro can be incredibly difficult

**Comment by McTsts** [comment]
I think it needs a different name then

**Comment by 12Metatron** [comment]
I agree, this could be a useful role to keep, but it should get a better name for sure. Maybe scared pyromancer, idk just a thought

**Comment by McTsts** [comment]
I think a better buffed pyromancer would be something that involves powdering in some way, e.g. immune against attacks of powdered people, so I think we should still remove this and add another buffed pyro instead.

**Comment by venomousbirds** [comment]
that would work

**Comment by venomousbirds** [comment]
didnt mean to not accept it

**Comment by McTsts** [comment]
@venomousbirds why did you close this then

**Comment by venomousbirds** [comment]
i meant to accept it but fucked up lmao

**Review by venomousbirds — APPROVED** [review]

**Pull request merged**
