### PR TITLE
Pack Tanner as Limited role

### PR DESCRIPTION
**Pull request by McTsts**
This isn't anything super fancy so I don't think accepting this as a limited role would be a problem

### CODE REVIEW

**Review by venomousbirds — APPROVED** [review]
Might even have potential as a slight buff to the wolfpack in big games?

**Comment by McTsts** [comment]
well yeah

**Comment by venomousbirds** [comment]
I meant as in, while it's a limited role, it has potential to become an actual recognized role

**Comment by McTsts** [comment]
oh yeah definitely. Just I think WIP roles usually are Limited ones first.

**Comment by venomousbirds** [comment]
Yeah that's true and it should be that way, I'm just acknowledging that Pack Tanner sounds like a great addition

**Comment by McTsts** [comment]
Yeah, we could try using it next game. I think using a few Limited roles in normal games is probably fine.

**Review by Dennis-0 — APPROVED** [review]

**Pull request merged**
