### PR TITLE
Change Reaper to SK

### LINKED ISSUE #603: Nightmare Team inconsistency
> wraith is SK but reaper isnt

@McTsts

### PR DESCRIPTION
**Pull request by ThomasRubycrust**
Fixes #603

### CODE REVIEW

**Review by cryptidjayden — APPROVED** [review]

**Comment by venomousbirds** [comment]
not sure if this is neccesary, its more power than killing

**Comment by McTsts** [comment]
> not sure if this is neccesary, its more power than killing

I agree, however with Wraith being SK I'd find it weird if this wasn't...

**Comment by venomousbirds** [comment]
we have teams in different categories with other alignments, so it's not inconsistent (example im taking is cm-cl so take that for what you will)
i think its better to focus on the correct categorization

**Comment by McTsts** [comment]
> we have teams in different categories with other alignments, so it's not inconsistent (example im taking is cm-cl so take that for what you will) i think its better to focus on the correct categorization

That misses the point. Wraith and Reaper share their power so they should also share their categorization.

**Comment by McTsts** [comment]
I'm unsure what to do about this. Reaper does feel more like a Solo Power, but its strange with it having the exact power of a Solo Killing role.

**Comment by venomousbirds** [comment]
i do think SP fits a lot better
wraith is no doubt a SK, it's only ability is killing sleepless players when they attack the Wraith
reaper has many more abilities that don't include killing, killing here isn't the main effect at all, just a passive 'protection'
the focus is way more on using the powers of the dead players, making it a SP
SK doesn't really fit

**Comment by McTsts** [comment]
I don't like it, but I think keeping it as SP is probably better.

**Pull request closed without merging**
