### PR TITLE
Create Mirror and Shiny Wolf

### PR DESCRIPTION
**Pull request by bobloy**
Power reflection abilities, for town and wolves

### CODE REVIEW

**Comment by McTsts** [comment]
The bad luck part seems kinda out of place in Mirror imo (and also seems too much like Angel/Despot)

**Comment by venomousbirds** [comment]
this is like some redirection role with a despot flair. not a big fan of redirection, and the despot thing should probably stay for despot only

**Comment by bobloy** [comment]
Removed the Mirror's curse, reduced just to a redirection ability.

**Comment by McTsts** [comment]
I think for now we don't want to add more redirections.

**Pull request closed without merging**
