### PR TITLE
Add Tasty Villager

### PR DESCRIPTION
**Pull request by bobloy**
A role used to balance town favored matches.

### CODE REVIEW

**Comment by McTsts** [comment]
Macho actually can't be killed no matter how many times you attack them.

**Comment by bobloy** [comment]
> Macho actually can't be killed no matter how many times you attack them.

Good to know, will remove Macho as an example.

**Comment by Shepherdwhen** [comment]
> I think a town role that balance in the wolves favor would be nice to have. I think right now we only have CC which is a very different playstyle.

I think another suggestion for one of these wolf favouring town roles was a town who is strongly disguised as wolf, possibly we should draft a PR for it

**Review by venomousbirds — CHANGES_REQUESTED** [review]
I don't think this role is useful, or fun to play. Your goal is to stay alive, yes, but town that favours wolves is not something I think we need in Werewolves. There's Wolf's Cub that practically does the same

**Comment by bobloy** [comment]
> I don't think this role is useful, or fun to play. Your goal is to stay alive, yes, but town that favours wolves is not something I think we need in Werewolves. There's Wolf's Cub that practically does the same

I disagree on it being useful. To use a 5 player game as an example: wolf cub would do nothing as a solo wolf, so that type of ability could only work on a town role.

As for it being fun to play, I think it's clearly more fun that citizen, and probably more fun than bard.

**Comment by McTsts** [comment]
> I don't think this role is useful, or fun to play. Your goal is to stay alive, yes, but town that favours wolves is not something I think we need in Werewolves. There's Wolf's Cub that practically does the same

CC is another wolfsided town role. This one could also be a nice addition to the Citizen/Journalist type of role category. This role could probably lead to an interesting playstyle, more so than CC as there's no risk of betrayal.

**Comment by McTsts** [comment]
> > I don't think this role is useful, or fun to play. Your goal is to stay alive, yes, but town that favours wolves is not something I think we need in Werewolves. There's Wolf's Cub that practically does the same
> 
> I disagree on it being useful. To use a 5 player game as an example: wolf cub would do nothing as a solo wolf, so that type of ability could only work on a town role.
> 
> As for it being fun to play, I think it's clearly more fun that citizen, and probably more fun than bard.

Semi-unrelated, but Bard is actually a fairly powerful role and can not be used like other weak TM's (Journalist, Citizen, this, maybe Child)

**Comment by Shepherdwhen** [comment]
> > I don't think this role is useful, or fun to play. Your goal is to stay alive, yes, but town that favours wolves is not something I think we need in Werewolves. There's Wolf's Cub that practically does the same
> 
> CC is another wolfsided town role. This one could also be a nice addition to the Citizen/Journalist type of role category. This role could probably lead to an interesting playstyle, more so than CC as there's no risk of betrayal.

CC is also very likely to be lynched if there is no attack and no runner claims, this is very unlikely to be lynched

**Comment by bobloy** [comment]
Some name suggestions other than Fat Guy:

Tasty Citizen
Catalyst
Accelerant
Sacrificial Lamb / Lamb
Buffet

**Comment by McTsts** [comment]
maybe Tasty Villager, because right now we don't do variants of Citizen

**Comment by McTsts** [comment]
This role will be added in v13

**Pull request merged**
