### PR TITLE
Make Guardian protect from NKs

### LINKED ISSUE #397: Guardian makes no sense
Guardian is the weakest / least useful of the elected role, but it's also the last one meaning it's entirely worthless - it's not even relevant to get the next elected role (like mayor sometimes is) either another elected role should be added or guardian should be buffed, probably.

### PR DESCRIPTION
**Pull request by McTsts**
Fixes #397

### CODE REVIEW

**Comment by McTsts** [comment]
Possibly announce who's protected?

**Comment by Shepherdwhen** [comment]
> Possibly announce who's protected?

Announce who was protected the night before?

**Comment by McTsts** [comment]
No, like the current guardian announces who's protected so lynching them isn't even an option (and you can't fail to lynch them) so it'd make sense to keep that part. Also, it's probably more interesting if you actually have to reveal who you're protecting.

**Comment by McTsts** [comment]
And, of course, it's not quite as powerful.

**Comment by Shepherdwhen** [comment]
I feel like part of it is wasting the enemy kills, if you announce who is protected before the kill happens the killer will kill someone else

**Comment by Shepherdwhen** [comment]
also this would just out the powerful roles to wolves

**Comment by Shepherdwhen** [comment]
meaning you couldn't protect a TI or anything only the mayor or reporter or guardian

**Comment by McTsts** [comment]
> I feel like part of it is wasting the enemy kills, if you announce who is protected before the kill happens the killer will kill someone else

But that's not part of how Guardian works. Current Guardian isn't meant to waste votes.

**Pull request merged**
